### PR TITLE
Developer

### PR DESCRIPTION
**Pull request by imrank03**

### CODE REVIEW

**Comment by nihalpasham** [comment]
> _ No description provided. _

Thanks for the PR. Can you add a few comments detailing what was changed?

**Comment by imrank03** [comment]
- The image header block diagram has been replaced in Section 4.1.

- Section 5.3 has been added for STM32F411.

**Comment by nihalpasham** [comment]
Looks good. Please submit an updated PR with revised (permanent) image links and please link the `repo` that hosts `svg` images to this thread.

**Review by nihalpasham — APPROVED** [review]
Looks good and nice job. The book looks good with some color.

**Comment by imrank03** [comment]
> Looks good. Please submit an updated PR with revised (permanent) image links and please link the `repo` that hosts `svg` images to this thread.

Here is a link to the repository https://github.com/imrank03/rustBoot-book-diagrams.git, if you modify an `image`, make sure not to modify the `image file name`.

**Comment by nihalpasham** [comment]
I have added a separate git workflow for pull requests. Can you update this pull request with an `upstream fetch` followed by a push?

**Review by nihalpasham — APPROVED** [review]
Looks good

**Pull request merged**
