### PR TITLE
rustBoot State diagram was added

### PR DESCRIPTION
**Pull request by UdayakumarHidakal**

### CODE REVIEW

**Comment by nihalpasham** [comment]
Some question and feedback:
- can we use `bullet-lists` rather `bulleted-numbers`?
- can we add a colour for each `true` or `false` description box?
- replace `match` with `check(s)` keyword and use a bullet-list for each check.
- change `call` to `jump` keyword
- I think we need to use different colours to indicate failures states or rollbacks.

**Comment by UdayakumarHidakal** [comment]
Review comments addressed.

**Review by imrank03 — CHANGES_REQUESTED** [review]
- Add your board to summary section and please make changes to contribute action.
- before commit check locally.

**Comment by UdayakumarHidakal** [comment]
- Changes addressed.

**Review by imrank03 — APPROVED** [review]

**Pull request closed without merging**
