### PR TITLE
Adding rustBoot flow diagram.

### PR DESCRIPTION
**Pull request by UdayakumarHidakal**
#8 rustBoot flow diagram updated.

### CODE REVIEW

**Review by sarath3192 — CHANGES_REQUESTED** [review]
A) If include a small table like
1. New state 0xFF
2. Update state 0x70
3. Testing state 0x10
4. success state 0x00

B) Add update partition state to 0xFF, after setting the success state 0x00 in the boot partition

C) If we create a flow diagram for Verify Integrity and authenticity and add that hyper link it will good

D) The spelling of authenticity is wrong in two boxes in the flowchart

**Review by sarath3192 — CHANGES_REQUESTED** [review]
Can we add a Ledger with below information
```
1. New state 0xFF
2. Update state 0x70
3. Testing state 0x10
4. success state 0x00
```
B) After setting the success state 0x00 in the boot partition, Can we add statement like erase the update partition.

C) If we can create a flow diagram for Verify Integrity and authenticity and add that hyper link it will good

D) The spelling of authenticity is wrong in two boxes in the flowchart please correct it

**Comment by nihalpasham** [comment]
Can we add a way to easily address different parts of the flow-chart. For example: if I wanted to refer to one of the boxes that does integrity verification, there must be an easier way.

**Comment by imrank03** [comment]
A few points I noticed
- can we change the `summing junction point` to `end point` after boot in success state `true`
- On the third `check`, can we extend the left arrow line which is too close.

**Review by imrank03 — CHANGES_REQUESTED** [review]
A few points I noticed
- can we change the summing junction point to end point after boot in success state true
- On the third check, can we extend the left arrow line which is too close.

**Comment by yashwanthsinghm** [comment]
Adding to the above comments made by sarath and imran.

1)"True i.e. Swapped firmware was not able to set the success state (0x00)" this statement should be included inside the box after true check.

**Review by nihalpasham — COMMENTED** [review]
I believe you're missing a few things.

- a note for the test ecc256 key
- remove WSL references
- and add a note for `cargo-binutils` as a pre-requisite

**Comment by nihalpasham** [comment]
looks good.

**Pull request merged**
