### PR TITLE
Linux system partitioning diagram added

### PR DESCRIPTION
**Pull request by imrank03**
- Linux partition diagram added.

### CODE REVIEW

**Review by nihalpasham — COMMENTED** [review]
- there is no need to modify `spellcheck.sh`. @Strange21 has submitted a PR with relevant changes for this. So, you can remove those changes.
- why have you added an extra `ci check` for broken links to `ci.yml`
- please add extra info to the linux-system partitioning image i.e. fat32 contains boot files and ext2/3/4 contains the root file system.

**Comment by imrank03** [comment]
Addressed review comments :

- removed spellcheck changes.
- removed extra ci check.
- added, extra info to the linux-system partitioning image.

**Comment by imrank03** [comment]
Modified the changes.

**Comment by nihalpasham** [comment]
looks good

**Pull request merged**
